### PR TITLE
Preset dates update

### PR DESCRIPTION
**Pull request by Keriganed**
Hi there. I've seen the preset dates have not been updated in a while, so I would like to request if it can be done. It's missing dates like wave 5 realease (2020-09-13), points update (2020-01-20) and wave 6 (2020-01-31). Also, xwd2 is outdated as wave 6 new stuff is not there yet.

Best regards,
Leo.

### CODE REVIEW

**Comment by haslo** [comment]
Hi Leo

This repo is for the old and defunct meta-wing - the current version at https://meta.listfortress.com/ lives in this repository: https://github.com/AlexRaubach/MetaWing

Can you please create the issue over there instead?

https://github.com/AlexRaubach/MetaWing/issues

Thanks!

Cheers,
Guido

**Comment by Keriganed** [comment]
I'm sorry, I was trying to create an issue in your page, but apparently GitHub is way too confusing to me. Your issue tab was not being shown as an option to me, and when I tryed to pull a request it was redirecting to haslo's one. I posted anyway hoping anything happens. It worked :D

I will try to post correctly now, I hope.

Best regards,
Leo.

________________________________
De: Guido Gloor Modjib <notifications@github.com>
Enviado: segunda-feira, 17 de fevereiro de 2020 06:20
Para: haslo/lists_juggle_browser <lists_juggle_browser@noreply.github.com>
Cc: Keriganed <leutpeut@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [haslo/lists_juggle_browser] Preset dates update (#100)


Hi Leo

This repo is for the old and defunct meta-wing - the current version at https://meta.listfortress.com/ lives in this repository: https://github.com/AlexRaubach/MetaWing

Can you please create the issue over there instead?

https://github.com/AlexRaubach/MetaWing/issues

Thanks!

Cheers,
Guido

**Comment by Keriganed** [comment]
I mean, you are haslo, aren't you?
*embarrassed

Well, I posted the issue there, correctly now, I guess.

________________________________
De: Guido Gloor Modjib <notifications@github.com>
Enviado: segunda-feira, 17 de fevereiro de 2020 06:20
Para: haslo/lists_juggle_browser <lists_juggle_browser@noreply.github.com>
Cc: Keriganed <leutpeut@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [haslo/lists_juggle_browser] Preset dates update (#100)


Hi Leo

This repo is for the old and defunct meta-wing - the current version at https://meta.listfortress.com/ lives in this repository: https://github.com/AlexRaubach/MetaWing

Can you please create the issue over there instead?

https://github.com/AlexRaubach/MetaWing/issues

Thanks!

Cheers,
Guido

**Comment by haslo** [comment]
I am, yeah 😁 Sorry for the confusion! The issue looks to be in the right place now, as far as I can tell.

I originally created meta-wing, but I've open sourced everything from the start. Other people have made it compatible with X-Wing 2.0, and I'm no longer maintaining it.

I'm actually not even playing X-Wing any more 😢

**Pull request closed without merging**
