### PR TITLE
Import of points and pilot skill for points based list

### PR DESCRIPTION
**Pull request by sirhaplo**
Hi, i've done a list of most used ships by point, using your code to import data from list juggler.
I dont know ruby, but i know sql.
I modified db and import and then did my queries.

Here's my post on reddit : https://www.reddit.com/r/XWingTMG/comments/7v1vt4/top_ship_builds_sorted_by_points/

These are the queries i used :

```sql
CREATE VIEW "squad_list" AS 
 SELECT squadrons.id AS sid,
    ship_configurations.id AS confid,
    factions.name AS faction,
	 pilots.id AS pid,	 
    pilots.name AS pname,
	 ships.name AS sname,
 	 pilots.skill AS pskill,
    pilots.points AS ppoints,    
    upgrades.id AS uid,
    upgrades.name AS uname,
    upgrades.points AS upoints,
    (case when squadrons.swiss_percentile is not null then squadrons.swiss_percentile else 0 end
	 +
    case when squadrons.elimination_percentile is not null then squadrons.elimination_percentile else 0 end) as perc
   FROM (((((((ship_configurations
     JOIN squadrons ON ((ship_configurations.squadron_id = squadrons.id)))
     JOIN tournaments ON ((squadrons.tournament_id = tournaments.id)))
     JOIN pilots ON ((pilots.id = ship_configurations.pilot_id)))
	  JOIN ships ON ((pilots.ship_id = ships.id)))
	  JOIN factions ON ((pilots.faction_id = factions.id)))
     JOIN ship_configurations_upgrades ON ((ship_configurations_upgrades.ship_configuration_id = ship_configurations.id)))
     JOIN upgrades ON ((ship_configurations_upgrades.upgrade_id = upgrades.id)))
  WHERE (tournaments.date > '2017-11-01'::date)
  ORDER BY ship_configurations.id, upgrades.id;

select pilot,max(ship) as ship, max(PS) as PS, max(faction) as faction,squad,max(points) as points,count(*) as total, avg(perc) as perc, avg(perc) * log(count(*)+1) as wPerc from 
(select confId,max(faction) as faction, max(sid) as squadron_id,max(pName) as pilot, max(sName) as ship,  max(pSkill) as PS, MAX(pPoints) + SUM(uPoints)  as points,array_agg(uName) as squad, max(perc) as perc
from squad_list
group by confId) as squads
group by pilot,squad
```

### CODE REVIEW

**Comment by haslo** [comment]
That looks neat! Thanks a lot for the PR. (I only edited to add Markdown for SQL syntax colors.)

As-is, it doesn't account for things like the Vaksai or the TIE Advanced title point reductions though, right? For example, the table in your Reddit post lists Vader with `Advanced Targeting Computer, TIE/x1, Adaptability (-1)` as 34, when it should be 30.

It might make sense to, instead of populating the fields like you did, use the per-squad values from 6ca94aa361a5fa6d0aeb9511d5ffb504da5c465f instead? Sozin added a v2 to his API that also gives us upgrade points, though meta-wing doesn't do anything with it yet. A JSON now looks like this:

```json
{
  "faction": "imperial",
  "pilots": [
    {
      "name": "rearadmiralchiraneau",
      "points": 46,
      "ship": "vt49decimator",
      "upgrades": {
        "crew": [
          {
            "name": "kyloren",
            "points": 3
          },
          {
            "name": "rebelcaptive",
            "points": 3
          },
          {
            "name": "gunner",
            "points": 5
          }
        ],
        "ept": [
          {
            "name": "predator",
            "points": 3
          }
        ],
        "mod": [
          {
            "name": "engineupgrade",
            "points": 4
          }
        ],
        "title": [
          {
            "name": "dauntless",
            "points": 2
          }
        ]
      }
    },
    {
      "name": "darthvader",
      "points": 29,
      "ship": "tieadvanced",
      "upgrades": {
        "ept": [
          {
            "name": "adaptability",
            "points": 0
          }
        ],
        "missile": [
          {
            "name": "harpoonmissiles",
            "points": 4
          }
        ],
        "mod": [
          {
            "name": "guidancechips",
            "points": 0
          }
        ],
        "system": [
          {
            "name": "advtargetingcomputer",
            "points": 5
          }
        ],
        "title": [
          {
            "name": "tiex1",
            "points": 0
          }
        ]
      }
    }
  ],
  "points": 100,
  "vendor": {
    "listjuggler": {}
  },
  "version": "4.2.0"
}
```

...though I just realized that it might not give us the correct values yet, either...

That would require changing `upoints` and picking it from the `squadrons` table instead, and right now, would require JSON selectors from in there (which psql has). But I don't really know about performance, that would need to be tested...

I'll give this some more thought, the idea is great!

**Comment by sirhaplo** [comment]
Happy that you liked it.
You are right about conditional discounts, my calculations don't count them.
It's seems that neither Sozin v2 does for singles ship ... but it does for the squadron.
I think that the total is entered by human at list creation.
This require to "read" the card ... or hard code a discount for some cards.

**Comment by lhayhurst** [comment]
It looks like I'm messing up the upgrade totals for tiex1 and vaksaii. I checked my code and indeed there was a bug (I was comparing the long name, 'Vaksai', versus the xws name, 'vaksai'. Oops.

see http://lists.starwarsclubhouse.com/api/v2/tournament/3891 (vaksai)
see http://lists.starwarsclubhouse.com/api/v2/tournament/3954 (tiex1)

**Comment by sirhaplo** [comment]
Nice, so it could be useful add a field points in the squadron table and sum up all point from the API, instead of sum up the original cards points.
Great job

**Comment by haslo** [comment]
Thanks @lhayhurst!

I think that field would have to be in the `ship_configurations` table, as that's where pilot and upgrades come together?

**Comment by haslo** [comment]
Sorry for letting this slide 😞 I'm about to make this repository readonly and closing everything. I have no idea whether it would still work with the current code base. Thanks a lot for your idea and contributions anyway!

**Pull request closed without merging**
